apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: stephengrider/multi-worker
      ports:
        - containerPort: 9999
      resources:
        limits:
          cpu: "500m" # 500 milliCPU (0.5 CPU cores)
          memory: "512Mi" # 512 Megabytes
        requests:
          cpu: "200m" # 200 milliCPU (0.2 CPU cores)
          memory: "256Mi" # 256 Megabytes